CC = gcc
CFLAGS = -Wall

hello: main.o hello.o
	$(CC) $(CFLAGS) main.o hello.o -o hello

main.o: main.c hello.h
	$(CC) $(CFLAGS) main.c -c

hello.o: hello.c hello.h
	$(CC) $(CFLAGS) hello.c -c

clean:
	rm -f *.o hello
